# -*- coding: utf-8 -*-
"""Lab W3D2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqsXsptO9BcsFxDOXnmQum94z5zuldWF
"""

!pip install transformers==4.45.2 accelerate

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

MODEL = "Qwen/Qwen2.5-1.5B-Instruct"

tok = AutoTokenizer.from_pretrained(MODEL)

tok.pad_token = tok.eos_token
tok.padding_side = "left"

model = AutoModelForCausalLM.from_pretrained(
    MODEL,
    torch_dtype=torch.float16,
    device_map="cuda"
)

print("Model loaded")

import time
import threading
from transformers import TextIteratorStreamer

def prompt_of_len(n_tokens: int) -> str:
    base = "Explain the following in detail.\n"
    filler = "A data center serves many inference requests at once. " * 600

    ids = tok(base + filler)["input_ids"][:n_tokens]

    return tok.decode(ids)

def measure_stream(prompt: str, new_tokens: int = 128):

    # تحويل النص إلى tokens
    enc = tok(prompt, return_tensors="pt").to("cuda")

    # تشغيل streaming
    streamer = TextIteratorStreamer(
        tok,
        skip_prompt=True,
        skip_special_tokens=True
    )

    kwargs = dict(
        **enc,
        max_new_tokens=new_tokens,
        do_sample=False,
        streamer=streamer
    )

    # تشغيل generate في thread منفصل
    th = threading.Thread(
        target=model.generate,
        kwargs=kwargs
    )

    # بداية الوقت
    t0 = time.time()

    th.start()

    stamps = []

    # كل مرة يصل token نسجل الوقت
    for _ in streamer:
        stamps.append(time.time())

    th.join()


    # TTFT = وقت أول token
    ttft = stamps[0] - t0


    # TPOT = متوسط الفرق بين tokens
    if len(stamps) > 1:
        gaps = [
            b-a for a,b in zip(stamps, stamps[1:])
        ]

        tpot = sum(gaps) / len(gaps)

    else:
        tpot = 0.0


    total = stamps[-1] - t0


    return {
        "ttft_s": round(ttft,4),
        "tpot_s": round(tpot,4),
        "total_s": round(total,4),
        "n_tokens": len(stamps)
    }

measure_stream(
    prompt_of_len(128),
    new_tokens=8
)

ttft_by_len = {}

for n in [128, 512, 2048]:

    r = measure_stream(prompt_of_len(n))

    ttft_by_len[str(n)] = r["ttft_s"]

    print(n, r)

import gc

def kv_formula_kb_per_token(
    layers=28,
    kv_heads=2,
    head_dim=128,
    dbytes=2
):
    return 2 * layers * kv_heads * head_dim * dbytes / 1024

formula = kv_formula_kb_per_token()

print("formula KB/token:", formula)

def cache_bytes(pkv):

    if hasattr(pkv, "key_cache"):

        tensors = list(pkv.key_cache) + list(pkv.value_cache)

    else:

        tensors = [
            t
            for layer in pkv
            for t in layer
        ]

    return sum(
        t.numel() * t.element_size()
        for t in tensors
    )

def measure_kv(context: int, new_tokens: int = 256):

    torch.cuda.empty_cache()
    gc.collect()

    torch.cuda.reset_peak_memory_stats()


    enc = tok(
        prompt_of_len(context),
        return_tensors="pt"
    ).to("cuda")


    before = torch.cuda.memory_allocated()


    out = model.generate(
        **enc,
        max_new_tokens=new_tokens,
        do_sample=False,
        use_cache=True,
        return_dict_in_generate=True
    )


    torch.cuda.synchronize()


    peak = torch.cuda.max_memory_allocated()


    total_tokens = out.sequences.shape[1]


    return {
        "context": context,

        "total_tokens": int(total_tokens),

        "peak_kb_per_token":
        round(
            (peak-before)
            / total_tokens
            /1024,
            1
        ),

        "kv_kb_per_token":
        round(
            cache_bytes(out.past_key_values)
            / total_tokens
            /1024,
            1
        )
    }

kv_rows = [
    measure_kv(c)
    for c in [512, 2048, 4096]
]


for r in kv_rows:
    print(r)

import json

with open("kv_check.json","w") as f:

    json.dump(
        {
        "formula_kb_per_token": formula,
        "measured_kb_per_token": kv_rows[-1]["kv_kb_per_token"],
        "peak_kb_per_token": kv_rows[-1]["peak_kb_per_token"]
        },
        f
    )

QUEUE = [32, 32, 32, 256] * 6

import time

def static_queue(
    batch,
    prompt="Explain what an inference server does."
):

    t0 = time.time()

    useful = 0
    slots = 0


    for i in range(0, len(QUEUE), batch):

        # أخذ مجموعة بحجم batch
        chunk = QUEUE[i:i+batch]


        # أطول طلب يحدد وقت الباتش
        n = max(chunk)


        # تجهيز النصوص
        enc = tok(
            [prompt] * len(chunk),
            return_tensors="pt",
            padding=True
        ).to("cuda")


        # تشغيل التوليد
        model.generate(
            **enc,
            max_new_tokens=n,
            do_sample=False
        )


        # عدد التوكنات المفيدة
        useful += sum(chunk)


        # عدد الأماكن التي عالجتها GPU
        slots += n * len(chunk)



    dt = time.time() - t0


    return {

        "batch": batch,

        "wall_s": round(dt,2),

        "tokens_per_s":
            round(useful/dt,1),

        "slot_efficiency":
            round(useful/slots,3)

    }

batch_rows = {}

for n in [1,4,8]:

    r = static_queue(n)

    batch_rows[str(n)] = r["tokens_per_s"]

    print(r)

import json

baselines = {

    "model": MODEL,

    "dtype": "fp16",

    "ttft_s": ttft_by_len,

    "tpot_s": measure_stream(
        prompt_of_len(512)
    )["tpot_s"],

    "batch": {
        k: v
        for k, v in batch_rows.items()
    }

}

with open("baselines.json", "w") as f:

    json.dump(
        baselines,
        f,
        indent=2
    )


print(
    json.dumps(
        baselines,
        indent=2
    )
)

from google.colab import files

files.download("baselines.json")

import json

with open("baselines.json", "r") as f:
    baselines = json.load(f)

# تحقق من وجود البيانات المطلوبة
checks = []

checks.append("model" in baselines)
checks.append("dtype" in baselines)
checks.append("ttft_s" in baselines)
checks.append("tpot_s" in baselines)
checks.append("batch" in baselines)

# تحقق أن TTFT أقل من الوقت الكلي
checks.append(
    all(
        baselines["ttft_s"][k] > 0
        for k in baselines["ttft_s"]
    )
)

# تحقق أن batch 8 موجود
checks.append("8" in baselines["batch"])

if all(checks):
    print("GREEN CHECK: PASS")
else:
    print("GREEN CHECK: FAIL")